### PR TITLE
updated import to explicitly include firestore

### PR DESCRIPTION
**Pull request by sykhan88**
I was getting an error firebase.firestore() is not a function when running without redux as part of your tutorial around the 1hr timestamp. nothing was getting written to Firestore. had to explicitly include firestore as per the answer here. https://stackoverflow.com/questions/46636255/firebase-firestore-is-not-a-function-when-trying-to-initialize-cloud-firestore?noredirect=1&lq=1. This is because firebase core does not include the firestore library.

### CODE REVIEW

**Comment by Yeghishe-Karapetyan** [comment]
> I was getting an error firebase.firestore() is not a function when running without redux as part of your tutorial around the 1hr timestamp. nothing was getting written to Firestore. had to explicitly include firestore as per the answer here. https://stackoverflow.com/questions/46636255/firebase-firestore-is-not-a-function-when-trying-to-initialize-cloud-firestore?noredirect=1&lq=1. This is because firebase core does not include the firestore library.

Friend can u say , what exactly did u do?

**Comment by sykhan88** [comment]
Just included firebase/firestore import if you see the changes in the pull request

**Comment by Yeghishe-Karapetyan** [comment]
> Just included firebase/firestore import if you see the changes in the pull request

Friend do you have discord, or Instagram, or Telegram, or Messenger, if yes please let me know, I have the same error but idk how can I add firebase/firestore, in my code or maybe it's another error, anyway thank you

**Comment by sykhan88** [comment]
Hi,
I would suggest github is the best way to correspond on this. This way the community can get involved as well and get to the bottom quicker. I have literally picked this up myself this weekend so wouldn't consider myself the go to person for answers. If you post your error in the issues for this repo, thats probably the best approach going forward.

**Comment by sykhan88** [comment]
In terms how to import, my issue was originating from the register.js file, where i was using firestore. Just added the import on top. See attached exampleimage

**Comment by Yeghishe-Karapetyan** [comment]
> In terms how to import, my issue was originating from the register.js file, where i was using firestore. Just added the import on top. See attached exampleimage

Thanks dude ;)

**Pull request merged**
