### PR TITLE
implemented the snapshot query fix from #19 issue

### PR DESCRIPTION
**Pull request by ChinmayMhatre**
I tried the fix for the snapshot query suggested in the issue #19   I suggest implementing this to avoid further confusion

### CODE REVIEW

**Comment by ChinmayMhatre** [comment]
@sykhan88 @SimCoderYoutube  could you take a look at this?

**Review by gxanshu — COMMENTED** [review]
well, i think you need to see that `const uid = snapshot.docs[0].ref.path.split('/')[1];` when i use this code then its works for me 🧐

**Comment by ChinmayMhatre** [comment]
> well, i think you need to see that `const uid = snapshot.docs[0].ref.path.split('/')[1];` when i use this code then its works for me 🧐

Yeah I have tried this . But I ran into problems when there are more than one posts . It only looks at the first one for some reason. The one I suggested worked for all of them hence the pr

**Comment by aianshume** [comment]
ok, i checked your code its work for me 👍

**Review by gxanshu — APPROVED** [review]
its OK 👍

**Comment by SimCoderYoutube** [comment]
I believe this problem has to do with the firebase version each one is using, could you make sure you update the package.json to match the version where this solution works?

Thank you 😊

**Comment by ChinmayMhatre** [comment]
> I believe this problem has to do with the firebase version each one is using, could you make sure you update the package.json to match the version where this solution works?
> 
> Thank you 😊

Yes sure ! I'll update it

**Comment by SimCoderYoutube** [comment]
Thank you chinmayMhatre!

Accepting your PR 😊

**Pull request merged**
